# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Format Code
      run: |
        python -m pip install --upgrade pip
        pip install black isort
        black .
        isort .
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest bandit safety coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Security Checks
      run: |
        bandit .
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: Coverage Reports
        path: htmlcov/index.html
        retention-days: 1
  
  train:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Train Model
      run: |
        python punkt.py
        python train.py
        
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: training-data
        path: |
          model.h5
          words.pkl
          tags.pkl
        retention-days: 1
    
  test-chatbot:
    runs-on: ubuntu-latest
    needs: train
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: training-data
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Test with Coverage
      run: |
        coverage erase
        coverage run -m pytest
        coverage html
  
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: Coverage Reports
        path: htmlcov/index.html
        retention-days: 1
